### PR TITLE
#36: update eslint config

### PR DESCRIPTION
**Pull request by Thisman**
#36 , I switched off some rules, because they cannot autofix. We need decide which errors should fixed

### CODE REVIEW

**Comment by xilaraux** [comment]
Nice PR!

**Comment by Thisman** [comment]
@PROPHESSOR Let's fix that errors list:

- consistent-return
- class-methods-use-this
- import/no-extraneous-dependencies
- prefer-const
- no-undef
- no-unused-expressions
- func-names
- no-shadow ( need refactoring )
- block-scoped-var ( need refactoring )
- one-var ( need refactoring )
- prefer-destructuring
- prefer-rest-param
- no-continue
- no-use-before-define
- no-var
- no-multi-assign
- no-unused-vars
- no-tabs
- global-require
- prefer-spread
- no-buffer-constructor
- no-sequences
- camelcase
- no-new-wrappers
- no-dupe-keys
- no-redeclare ( refactoring )
- array-callback-return
- no-unreachable
- no-cond-assign
- brace-style
- no-restricted-globals
- import/no-unresolved
- guard-for-in
- no-lone-blocks
- no-new-object
- no-empty
- no-lonely-if
- defult-case
- no-inner-declarations
- new-cap
- no-constant-condition
- no-new-require
- no-loop-func
- vars-on-top

**Comment by Thisman** [comment]
@PROPHESSOR what with this PR?

**Comment by PROPHESSOR** [comment]
@Thisman 
I don't know...
Now eslintrc looks terrible.
I just need to sit down and do it, but not enough time.

**Pull request closed without merging**
